debug

diff --git a/.github/workflows/publish-image.yaml b/.github/workflows/publish-image.yaml
--- a/.github/workflows/publish-image.yaml
+++ b/.github/workflows/publish-image.yaml
@@ -17,6 +17,12 @@ jobs:
     
     # Ensure Nix and Docker are set up
     steps:
+
+    - name: Debug login
+      run: |
+      echo "Attempting login with actor: ${{ github.actor }}"
+      docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 2>&1 || echo "Login failed"
+
     - name: Checkout code
       uses: actions/checkout@v4
 
